<h1>TASK 1</h1>

<h3>1. Limpeza dos dados</h3>

In [1]:
# importando bibliotecas iniciais para fazer a limpeza
import pandas as pd
import numpy as np

In [2]:
# baixando o dataset
df = pd.read_excel('dataset.xlsx')
df.head()

,Patient ID,Patient age quantile,SARS-Cov-2 exam result,"Patient addmited to regular ward (1=yes, 0=no)","Patient addmited to semi-intensive unit (1=yes, 0=no)","Patient addmited to intensive care unit (1=yes, 0=no)",Hematocrit,Hemoglobin,Platelets,Mean platelet volume,...,Hb saturation (arterial blood gases),pCO2 (arterial blood gas analysis),Base excess (arterial blood gas analysis),pH (arterial blood gas analysis),Total CO2 (arterial blood gas analysis),HCO3 (arterial blood gas analysis),pO2 (arterial blood gas analysis),Arteiral Fio2,Phosphor,ctO2 (arterial blood gas analysis)
0,44477f75e8169d2,13,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,126e9dd13932f68,17,negative,0,0,0,0.236515,-0.02234,-0.517413,0.010677,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a46b4402a0e5696,8,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f7d619a94f97c45,5,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,d9e41465789c2b5,15,negative,0,0,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<p>Inicialmente eu tentei ignorar os valores que estÃ£o faltando (NaN).</p>
<p>Aqui eu vou tentar uma abordagem diferente: vou dar replace nesses valores. O valor que vou imputar serÃ¡ a mÃ©dia dos valores presentes</p>

In [3]:
numerics = ['float32', 'float64']
df_aux = df.select_dtypes(include=numerics).apply(lambda x: x.fillna(x.median()),axis=0)
drop_columns = []
for i in df_aux.columns:
    drop_columns.append(i)
df = df.drop(drop_columns, axis = 1) 

df = pd.concat([df, df_aux], axis=1, sort=False)
df.head()

,Patient ID,Patient age quantile,SARS-Cov-2 exam result,"Patient addmited to regular ward (1=yes, 0=no)","Patient addmited to semi-intensive unit (1=yes, 0=no)","Patient addmited to intensive care unit (1=yes, 0=no)",Respiratory Syncytial Virus,Influenza A,Influenza B,Parainfluenza 1,...,Hb saturation (arterial blood gases),pCO2 (arterial blood gas analysis),Base excess (arterial blood gas analysis),pH (arterial blood gas analysis),Total CO2 (arterial blood gas analysis),HCO3 (arterial blood gas analysis),pO2 (arterial blood gas analysis),Arteiral Fio2,Phosphor,ctO2 (arterial blood gas analysis)
0,44477f75e8169d2,13,negative,0,0,0,NaN,NaN,NaN,NaN,...,0.267769,-0.21208,-0.011817,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693
1,126e9dd13932f68,17,negative,0,0,0,not_detected,not_detected,not_detected,not_detected,...,0.267769,-0.21208,-0.011817,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693
2,a46b4402a0e5696,8,negative,0,0,0,NaN,NaN,NaN,NaN,...,0.267769,-0.21208,-0.011817,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693
3,f7d619a94f97c45,5,negative,0,0,0,NaN,NaN,NaN,NaN,...,0.267769,-0.21208,-0.011817,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693
4,d9e41465789c2b5,15,negative,0,0,0,not_detected,not_detected,not_detected,not_detected,...,0.267769,-0.21208,-0.011817,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693

<p>Na minha tentativa anterior eu usei todas as features relacionadas com exames da maneira como elas vieram. Dessa vez, vou seguir umas dicas que consegui e fundir algumas colunas em uma Ãºnica coluna, agrupando vÃ­rus parecidos</p>

In [4]:
df['Influenza A'] = np.where(df['Influenza A'] == "detected",1,0)
df['Influenza B'] = np.where(df['Influenza B'] == "detected",1,0)
df['Influenza'] = np.where((df['Influenza A'] + df['Influenza B']) >= 1,1,0)
df['Parainfluenza 1'] = np.where(df['Parainfluenza 1'] == "detected",1,0)
df['Parainfluenza 2'] = np.where(df['Parainfluenza 2'] == "detected",1,0)
df['Parainfluenza 3'] = np.where(df['Parainfluenza 3'] == "detected",1,0)
df['Parainfluenza 4'] = np.where(df['Parainfluenza 4'] == "detected",1,0)
df['Parainfluenza'] = np.where((df['Parainfluenza 1']+ df['Parainfluenza 2'] + df['Parainfluenza 3']
                                   + df['Parainfluenza 4']) >= 1,1,0)
df['Coronavirus229E'] = np.where(df['Coronavirus229E'] == "detected",1,0)
df['CoronavirusNL63'] = np.where(df['CoronavirusNL63'] == "detected",1,0)
df['Coronavirus HKU1'] = np.where(df['Coronavirus HKU1'] == "detected",1,0)
df['CoronavirusOC43'] = np.where(df['CoronavirusOC43'] == "detected",1,0)
df['Coronavirus'] = np.where((df['Coronavirus HKU1']+ df['Coronavirus229E'] + df['CoronavirusNL63']
                              + df['CoronavirusOC43']) >= 1,1,0)
df = df.drop(['Influenza A','Influenza B' ,'Parainfluenza 1','Parainfluenza 2','Parainfluenza 3','Parainfluenza 4'
             ,'Coronavirus229E','CoronavirusNL63','Coronavirus HKU1','CoronavirusOC43'], axis = 1)

<p>Agora eu vou filtrar as features que tÃªm mais de 90% dos dados faltando. E vou simplesmente apagar essas colunas.</p>

In [5]:
nan_pct = (df.isna().sum()/len(df))
nan_pct = dict(nan_pct)

In [6]:
columns_to_drop = []
for feature in nan_pct:
    if nan_pct[feature] > 0.9:
        columns_to_drop.append(feature)
df = df.drop(columns_to_drop, axis=1)

<p>Por Ãºltimo, vou usar OneHotEncoder para transformar as colunas variÃ¡veis binÃ¡rias</p>

In [7]:
from category_encoders.one_hot import OneHotEncoder
oh = OneHotEncoder(cols= ['Respiratory Syncytial Virus','Rhinovirus/Enterovirus' ,'Chlamydophila pneumoniae'
                            ,'Metapneumovirus','Bordetella pertussis','Patient age quantile','Influenza A, rapid test'
                            ,'Influenza B, rapid test','Adenovirus','Inf A H1N1 2009'
                            ],use_cat_names=True)
oh.fit(df)
df = oh.transform(df)
df = df.replace({'positive':1,'negative':0})
df

,Patient ID,Patient age quantile_13.0,Patient age quantile_17.0,Patient age quantile_8.0,Patient age quantile_5.0,Patient age quantile_15.0,Patient age quantile_9.0,Patient age quantile_16.0,Patient age quantile_1.0,Patient age quantile_14.0,...,pH (arterial blood gas analysis),Total CO2 (arterial blood gas analysis),HCO3 (arterial blood gas analysis),pO2 (arterial blood gas analysis),Arteiral Fio2,Phosphor,ctO2 (arterial blood gas analysis),Influenza,Parainfluenza,Coronavirus
0,44477f75e8169d2,1,0,0,0,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
1,126e9dd13932f68,0,1,0,0,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
2,a46b4402a0e5696,0,0,1,0,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
3,f7d619a94f97c45,0,0,0,1,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
4,d9e41465789c2b5,0,0,0,0,1,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,ae66feb9e4dc3a0,0,0,0,0,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
5640,517c2834024f3ea,0,1,0,0,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
5641,5c57d6037fe266d,0,0,0,0,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
5642,c20c44766f28291,0,0,0,0,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0
5643,2697fdccbfeb7f7,0,0,0,0,0,0,0,0,0,...,0.294202,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0

<h3>2. Realizando testes</h3>

In [8]:
# criando dataframes de treino e teste
from sklearn.model_selection import train_test_split

X = df.drop(['Patient ID','SARS-Cov-2 exam result'], axis=1)
y = df['SARS-Cov-2 exam result']

#20% test e 80% train
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

<p>Vou usar cinco tipos de modelos aqui:</p>
<ul>
    <li>Logistic regression;</li>
    <li>Support Vector Machine;</li>
    <li>Random Forest;</li>
    <li>XGboost;</li>
    <li>Voting Classifier</li>
</ul>

In [9]:
from sklearn.metrics import f1_score,accuracy_score
from sklearn.ensemble import RandomForestClassifier,VotingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

rf = RandomForestClassifier(max_depth=5, random_state=42,n_estimators=100,class_weight = 'balanced')
rf.fit(X_train,y_train)
y_pred_rf = rf.predict(X_test)
print('accuracy:' , accuracy_score(y_pred_rf,y_test))
print('f1_score:' , f1_score(y_pred_rf,y_test,average='weighted'))

accuracy: 0.46944198405668736
f1_score: 0.3787009575316095

In [10]:
lr = LogisticRegression(class_weight = 'balanced', solver = 'liblinear',penalty="l1")
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)
print('accuracy:' , accuracy_score(y_pred_lr,y_test))
print('f1_score:' , f1_score(y_pred_lr,y_test,average='weighted'))

accuracy: 0.5438441098317095
f1_score: 0.4544272722936762

In [11]:
svc = SVC(gamma='auto',random_state=42)
svc.fit(X_train, y_train)
y_pred_svc = svc.predict(X_test)
print('f1_score:' , f1_score(y_pred_svc,y_test,average='weighted'))
print('accuracy:' , accuracy_score(y_pred_svc,y_test))

f1_score: 0.9497674418604651
accuracy: 0.9043401240035429

In [12]:
import xgboost as xgb
xgboost = xgb.XGBClassifier(learning_rate = 0.2
                            ,max_depth = 5
                            ,colsample_bytree = 0.9
                            ,n_estimators = 100
                            ,random_state=42
                            ,class_weight='balanced'
                           )

xgboost.fit(X_train,y_train)
y_pred_xg = xgboost.predict(X_test)
print('f1_score:' , f1_score(y_pred_xg,y_test,average='weighted'))
print('accuracy:' , accuracy_score(y_pred_xg,y_test))

f1_score: 0.9412223399179727
accuracy: 0.9096545615589017

In [13]:
stacking = VotingClassifier(estimators=[
    ('rf', rf), ('lr',lr),('xgboost',xgboost),('svc',svc)], voting='hard')
stacking.fit(X_train, y_train)
y_pred_vc = stacking.predict(X_test)
print('f1_score:' , f1_score(y_pred_vc,y_test,average='weighted'))
print('accuracy:' , accuracy_score(y_pred_vc,y_test))

f1_score: 0.942412011533486
accuracy: 0.9105403011514615

# TASK 2

<h3>1. Preparando colunas sobre tipo de internaÃ§Ã£o</h3>

<p>Para nÃ£o usar trÃªs colunas na minha previsÃ£o, eu sintetizei elas em um Ãºnica usando um sistema de cÃ³digo</p>

In [14]:
patient_addmited_type = []
for i in df.index:
    code = str(df['Patient addmited to intensive care unit (1=yes, 0=no)'][i]) + str(df['Patient addmited to regular ward (1=yes, 0=no)'][i]) + str(df['Patient addmited to semi-intensive unit (1=yes, 0=no)'][i])
    if code == '000':
        patient_addmited_type.append(0)
    elif code == '100':
        patient_addmited_type.append(3)
    elif code == '010':
        patient_addmited_type.append(1)
    elif code == '001':
        patient_addmited_type.append(2)
df['Patient addmited type'] = patient_addmited_type

In [15]:
df = df.drop(['Patient addmited to intensive care unit (1=yes, 0=no)',
             'Patient addmited to regular ward (1=yes, 0=no)',
             'Patient addmited to semi-intensive unit (1=yes, 0=no)'], axis=1)
df.head()

,Patient ID,Patient age quantile_13.0,Patient age quantile_17.0,Patient age quantile_8.0,Patient age quantile_5.0,Patient age quantile_15.0,Patient age quantile_9.0,Patient age quantile_16.0,Patient age quantile_1.0,Patient age quantile_14.0,...,Total CO2 (arterial blood gas analysis),HCO3 (arterial blood gas analysis),pO2 (arterial blood gas analysis),Arteiral Fio2,Phosphor,ctO2 (arterial blood gas analysis),Influenza,Parainfluenza,Coronavirus,Patient addmited type
0,44477f75e8169d2,1,0,0,0,0,0,0,0,0,...,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0,0
1,126e9dd13932f68,0,1,0,0,0,0,0,0,0,...,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0,0
2,a46b4402a0e5696,0,0,1,0,0,0,0,0,0,...,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0,0
3,f7d619a94f97c45,0,0,0,1,0,0,0,0,0,...,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0,0
4,d9e41465789c2b5,0,0,0,0,1,0,0,0,0,...,0.077435,0.056332,-0.159955,-0.011744,-0.138182,0.182693,0,0,0,0

In [16]:
X_2 = df.drop(['Patient ID','Patient addmited type'], axis=1)
y_2 = df['Patient addmited type']
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2,y_2,test_size=0.2,random_state=42)

In [18]:
svc2 = SVC(gamma='auto',random_state=42)
svc2.fit(X_train_2, y_train_2)
y_pred_svc_2 = svc2.predict(X_test_2)
print('f1_score:' , f1_score(y_pred_svc_2,y_test_2,average='weighted'))
print('accuracy:' , accuracy_score(y_pred_svc_2,y_test_2))

f1_score: 0.9824245155475437
accuracy: 0.9654561558901683

In [19]:
xgboost2 = xgb.XGBClassifier(learning_rate = 0.2
                            ,max_depth = 5
                            ,colsample_bytree = 0.9
                            ,n_estimators = 100
                            ,random_state=42
                            ,class_weight='balanced'
                           )

xgboost2.fit(X_train_2,y_train_2)
y_pred_xg_2 = xgboost2.predict(X_test_2)
print('f1_score:' , f1_score(y_pred_xg_2,y_test_2,average='weighted'))
print('accuracy:' , accuracy_score(y_pred_xg_2,y_test_2))

f1_score: 0.9768357395121843
accuracy: 0.9672276350752879